#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "norish"
name = "Norish"
description.en = "Norish is a shared recipe app"
description.fr = "Norish est une application de recettes de cuisine partagÃ©es"

version = "0.13.6~ynh1"

maintainers = ["bowgartfield"]

[upstream]
license = "AGPL-3.0-only" # you can see the available licenses identifiers list here: https://spdx.org/licenses/
website = "https://example.com"
demo = "https://imgur.com/a/norish-small-demo-07VpBIc"
admindoc = "https://github.com/norish-recipes/norishe"
code = "https://github.com/norish-recipes/norishe"
fund = "https://buymeacoffee.com/mikevanes"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "200M"
ram.build = "200M"
ram.runtime = "200M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/norish"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    # this is a generic question - ask strings are automatically handled by YunoHost's core
    type = "user"


[resources]

    [resources.sources]

    [resources.sources.main]
    url = "https://github.com/norish-recipes/norish/archive/refs/tags/v0.13.6-beta.tar.gz"
    sha256 = "1a47b953631e18618fe36cc88c701c56f6d189917fcd5278c11139547cebd782"
    autoupdate.strategy = "latest_github_tag"

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]

    [resources.apt]
    packages = ""

    [resources.database]
    # This will automatically provision/deprovison a MySQL DB and store the corresponding credentials in settings $db_user, $db_name, $db_pwd
    type = "postgresql"
