#:schema https://raw.githubusercontent.com/YunoHost/apps/main/schemas/manifest.v2.schema.json

packaging_format = 2

id = "norish"
name = "Norish"
description.en = "Norish is a shared recipe app"
description.fr = "Norish est une application de recettes de cuisine partagÃ©es"

version = "0.13.6~ynh1"

maintainers = ["bowgartfield"]

[upstream]
license = "AGPL-3.0-only"
website = "https://github.com/norish-recipes"
demo = "https://imgur.com/a/norish-small-demo-07VpBIc"
admindoc = "https://github.com/norish-recipes"
code = "https://github.com/norish-recipes"
fund = "https://buymeacoffee.com/mikevanes"

[integration]
yunohost = ">= 12.0.9"
helpers_version = "2.1"
architectures = "all"
multi_instance = true

ldap = "not_relevant"
sso = "not_relevant"

disk = "500M"
ram.build = "3000M"
ram.runtime = "512M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/norish"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.admin]
    type = "user"

[resources]

    [resources.sources.main]
    url = "https://github.com/norish-recipes/norish/archive/refs/tags/v0.13.6-beta.tar.gz"
    sha256 = "1a47b953631e18618fe36cc88c701c56f6d189917fcd5278c11139547cebd782"
    autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]

    [resources.permissions]
    main.url = "/"

    [resources.ports]
    main.default = 3000
    chromium.default = 9222

    [resources.apt]
    packages = "chromium, ffmpeg"

    [resources.database]
    type = "postgresql"

    [resources.nodejs]
    version = "22"
